# Generated by Django 5.0.6 on 2024-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
