# Generated by Django 5.0.6 on 2024-05-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_reviewrating_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
